version: '3.7'

services:
    android-academy:
        build: ./docker/${APP_ENV}/php
        container_name: ${APP_NAME}
        environment:
            PHP_IDE_CONFIG: "serverName=android-academy.local"
            XDEBUG_CONFIG: "remote_host=192.168.13.243"
        volumes:
            - ./code:/var/www/${APP_NAME}:cached
    nginx:
        build: ./docker/${APP_ENV}/nginx
        container_name: ${APP_NAME}-nginx
        ports:
            - 8008:8008
        links:
            - android-academy
        volumes:
            - ./code:/var/www/${APP_NAME}:cached
    mysql:
        container_name: ${APP_NAME}-mysql
        image: percona:5.7
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        ports:
            - 3306:3306
        volumes:
            - ./database:/${APP_NAME}:cached
    redis:
        image: redis:alpine
        container_name: swapp_redis