services:
    _defaults:
        public: true
    app.authentication.controller:
        class: App\Controller\PublicController
        arguments:
            - '@app.security.authentication_service'
