services:
    _defaults:
        public: true
    app.authentication.controller:
        class: App\Controller\PublicController
        arguments:
            - '@app.security.authentication_service'
    app.mentors.controller:
        class: App\Controller\SecuredController
        arguments:
            - '@App\Service\MentorsService'
#
    app.events.controller:
        class: App\Controller\SecuredController
        arguments:
            - '@App\Service\EventsService'
    app.event.controller:
        class: App\Controller\SecuredController
        arguments:
            - '@App\Service\EventService'
#
    app.resource_links.controller:
        class: App\Controller\SecuredController
        arguments:
            - '@App\Service\ResourceLinksService'

#
    app.register_to_event.controller:
        class: App\Controller\SecuredController
        arguments:
            - '@App\Service\RegisterEventService'