services:
    _defaults:
        public: true
    app.authentication.controller:
        class: App\Controller\PublicController
        arguments:
            - '@app.security.authentication_service'
    app.mentors.controller:
        class: App\Controller\SecuredController
        arguments:
            - '@App\Service\MentorsService'
