auth:
    path: /auth
    defaults: {_controller: 'app.authentication.controller:invoke'}
    methods: [POST]

mentors:
    path: /mentors
    defaults: {_controller: 'app.mentors.controller:invoke'}
    methods: [GET]

events:
    path: /events
    defaults: {_controller: 'app.events.controller:invoke'}
    methods: [GET]