auth:
    path: /auth
    defaults: {_controller: 'app.authentication.controller:invoke'}
    methods: [POST]

mentors:
    path: /mentors
    defaults: {_controller: 'app.mentors.controller:invoke'}
    methods: [GET]

events:
    path: /events
    defaults: {_controller: 'app.events.controller:invoke'}
    methods: [GET]

event:
    path: /event
    defaults: {_controller: 'app.event.controller:invoke'}
    methods: [GET]

resource_links:
    path: /resource-links
    defaults: {_controller: 'app.resource_links.controller:invoke'}
    methods: [GET]

register_to_event:
    path: /register-event
    defaults: {_controller: 'app.register_to_event.controller:invoke'}
    methods: [POST]

profile:
    path: /profile
    defaults: {_controller: 'app.profile.controller:invoke'}
    methods: [GET]