App\Entity\EventTicket:
    table: event_tickets
    type: entity
    repositoryClass: App\Repository\EventTicketRepository
    id:
        id:
            type: integer
            generator: {strategy: AUTO}
    fields:
        is_confirmed:
            type: boolean
            options:
                default: 0
        is_visited:
            type: boolean
            options:
                default: 0
    manyToOne:
        user:
            targetEntity: App\Entity\User
            joinColumn:
                name: user
                referencedColumnName: id
        event:
            targetEntity: App\Entity\Event
            joinColumn:
                name: event
                referencedColumnName: id