App\Entity\Region:
    table: regions
    type: entity
    repositoryClass: App\Repository\RegionRepository
    id:
        id:
            type: integer
            generator: {strategy: AUTO}
    fields:
        title:
            type: string
            length: 50