services:
    app.security.authentication_service:
        class: App\Security\Service\AuthenticationService
        public: true
        arguments:
            - '@sb_redis.client.default'
            - '@App\Repository\UserRepository'
            - '@App\Security\Generator\SmsCodeGenerator'
            - '@app.infrastructure.storage.redis_sms_code'
            - '@App\Security\Validator\SmsCodeValidator'

    data_fixtures.provider.user:
        class: App\DataFixtures\Faker\Provider\UserProvider
        tags: [ { name: nelmio_alice.faker.provider } ]

    data_fixtures.provider.course:
        class: App\DataFixtures\Faker\Provider\CourseProvider
        tags: [ { name: nelmio_alice.faker.provider } ]

    data_fixtures.provider.resource_link:
        class: App\DataFixtures\Faker\Provider\ResourceLinkProvider
        tags: [ { name: nelmio_alice.faker.provider } ]

    data_fixtures.provider.event:
        class: App\DataFixtures\Faker\Provider\EventProvider
        tags: [ { name: nelmio_alice.faker.provider } ]