security:
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        api:
            id: app.security.redis_user_provider
            # id: App\Security\Provider\RedisUserProvider
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            stateless: true
            anonymous: ~
            #loguot: ~
            guard:
                authenticators:
                    - App\Security\Authenticator\TokenAuthenticator

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # https://symfony.com/doc/current/security/form_login_setup.html